import type { BattleMusicTrack } from './BattleMusic';

// Generated by `npm run music:manifest`. Do not edit by hand.
export const LOBBY_MUSIC_TRACKS: readonly BattleMusicTrack[] = [
  {
    "id": "alex-morgan-downtempo-chill-electronic",
    "artist": "Alex Morgan",
    "title": "Downtempo Chill Electronic",
    "filename": "alex-morgan-downtempo-chill-electronic-528322.mp3",
    "src": "/audio/lobby-music/alex-morgan-downtempo-chill-electronic-528322.mp3",
    "durationSeconds": 198.792
  },
  {
    "id": "alex-morgan-melodic-techno-journey",
    "artist": "Alex Morgan",
    "title": "Melodic Techno Journey",
    "filename": "alex-morgan-melodic-techno-journey-537492.mp3",
    "src": "/audio/lobby-music/alex-morgan-melodic-techno-journey-537492.mp3",
    "durationSeconds": 303.96
  },
  {
    "id": "jeff-guo-claude-s-plan",
    "artist": "Jeff Guo",
    "title": "Claude's Plan",
    "filename": "Claude's Plan.mp3",
    "src": "/audio/lobby-music/Claude's%20Plan.mp3",
    "durationSeconds": 197.825
  },
  {
    "id": "directtodreams-gravity",
    "artist": "Directtodreams",
    "title": "Gravity",
    "filename": "directtodreams-gravity-383096.mp3",
    "src": "/audio/lobby-music/directtodreams-gravity-383096.mp3",
    "durationSeconds": 136.934
  },
  {
    "id": "directtodreams-strange-galaxy",
    "artist": "Directtodreams",
    "title": "Strange Galaxy",
    "filename": "directtodreams-strange-galaxy-383105.mp3",
    "src": "/audio/lobby-music/directtodreams-strange-galaxy-383105.mp3",
    "durationSeconds": 91.533
  },
  {
    "id": "lmnt-studio-chill-house",
    "artist": "Lmnt Studio",
    "title": "Chill House",
    "filename": "lmnt_studio-chill_house-419916.mp3",
    "src": "/audio/lobby-music/lmnt_studio-chill_house-419916.mp3",
    "durationSeconds": 138.998
  },
  {
    "id": "lmnt-studio-the-fashion-house",
    "artist": "Lmnt Studio",
    "title": "The Fashion House",
    "filename": "lmnt_studio-the_fashion_house-419905.mp3",
    "src": "/audio/lobby-music/lmnt_studio-the_fashion_house-419905.mp3",
    "durationSeconds": 118.518
  },
  {
    "id": "maison-brava-deep-chill-lounge-remix",
    "artist": "Maison Brava",
    "title": "Deep Chill Lounge Remix",
    "filename": "maison_brava-deep-chill-lounge-remix-372691.mp3",
    "src": "/audio/lobby-music/maison_brava-deep-chill-lounge-remix-372691.mp3",
    "durationSeconds": 183.888
  },
  {
    "id": "maison-brava-piano-intro",
    "artist": "Maison Brava",
    "title": "Piano Intro",
    "filename": "maison_brava-piano-intro-392162.mp3",
    "src": "/audio/lobby-music/maison_brava-piano-intro-392162.mp3",
    "durationSeconds": 160.032
  },
  {
    "id": "missywhimsyart-step-to-the-beat",
    "artist": "Missywhimsyart",
    "title": "Step To The Beat",
    "filename": "missywhimsyart-step_to_the_beat-244653.mp3",
    "src": "/audio/lobby-music/missywhimsyart-step_to_the_beat-244653.mp3",
    "durationSeconds": 228.96
  },
  {
    "id": "tokyorifft-maggie-the-muscle",
    "artist": "Tokyorifft",
    "title": "Maggie The Muscle",
    "filename": "tokyorifft-maggie_the-muscle-512637.mp3",
    "src": "/audio/lobby-music/tokyorifft-maggie_the-muscle-512637.mp3",
    "durationSeconds": 212.64
  }
];
