import type { BattleMusicTrack } from './BattleMusic';

// Generated by `npm run music:manifest`. Do not edit by hand.
export const LOBBY_MUSIC_TRACKS: readonly BattleMusicTrack[] = [
  {
    "id": "alex-morgan-downtempo-chill-electronic",
    "artist": "Alex Morgan",
    "title": "Downtempo Chill Electronic",
    "filename": "alex-morgan-downtempo-chill-electronic-528322.mp3",
    "src": "/audio/lobby-music/alex-morgan-downtempo-chill-electronic-528322.mp3",
    "durationSeconds": 198.792
  },
  {
    "id": "alex-morgan-melodic-techno-journey",
    "artist": "Alex Morgan",
    "title": "Melodic Techno Journey",
    "filename": "alex-morgan-melodic-techno-journey-537492.mp3",
    "src": "/audio/lobby-music/alex-morgan-melodic-techno-journey-537492.mp3",
    "durationSeconds": 303.96
  },
  {
    "id": "directtodreams-gravity",
    "artist": "Directtodreams",
    "title": "Gravity",
    "filename": "directtodreams-gravity-383096.mp3",
    "src": "/audio/lobby-music/directtodreams-gravity-383096.mp3",
    "durationSeconds": 136.934
  },
  {
    "id": "directtodreams-strange-galaxy",
    "artist": "Directtodreams",
    "title": "Strange Galaxy",
    "filename": "directtodreams-strange-galaxy-383105.mp3",
    "src": "/audio/lobby-music/directtodreams-strange-galaxy-383105.mp3",
    "durationSeconds": 91.533
  },
  {
    "id": "maison-brava-deep-chill-lounge-remix",
    "artist": "Maison Brava",
    "title": "Deep Chill Lounge Remix",
    "filename": "maison_brava-deep-chill-lounge-remix-372691.mp3",
    "src": "/audio/lobby-music/maison_brava-deep-chill-lounge-remix-372691.mp3",
    "durationSeconds": 183.888
  },
  {
    "id": "maison-brava-piano-intro",
    "artist": "Maison Brava",
    "title": "Piano Intro",
    "filename": "maison_brava-piano-intro-392162.mp3",
    "src": "/audio/lobby-music/maison_brava-piano-intro-392162.mp3",
    "durationSeconds": 160.032
  }
];
