import type { BattleMusicTrack } from './BattleMusic';

// Generated by `npm run music:manifest`. Do not edit by hand.
export const BATTLE_MUSIC_TRACKS: readonly BattleMusicTrack[] = [
  {
    "id": "psychronic-acid-prophet",
    "artist": "Psychronic",
    "title": "Acid Prophet",
    "filename": "Psychronic - Acid Prophet.mp3",
    "src": "/audio/music/Psychronic%20-%20Acid%20Prophet.mp3",
    "durationSeconds": 315
  },
  {
    "id": "psychronic-battlecube-arena",
    "artist": "Psychronic",
    "title": "Battlecube Arena",
    "filename": "Psychronic - Battlecube Arena.mp3",
    "src": "/audio/music/Psychronic%20-%20Battlecube%20Arena.mp3",
    "durationSeconds": 233.232
  },
  {
    "id": "psychronic-break-forward",
    "artist": "Psychronic",
    "title": "Break Forward",
    "filename": "Psychronic - Break Forward.mp3",
    "src": "/audio/music/Psychronic%20-%20Break%20Forward.mp3",
    "durationSeconds": 222.48
  },
  {
    "id": "psychronic-clockwork-ascension-alt",
    "artist": "Psychronic",
    "title": "Clockwork Ascension (Alt)",
    "filename": "Psychronic - Clockwork Ascension (Alt).mp3",
    "src": "/audio/music/Psychronic%20-%20Clockwork%20Ascension%20(Alt).mp3",
    "durationSeconds": 331.872
  },
  {
    "id": "psychronic-clockwork-ascension",
    "artist": "Psychronic",
    "title": "Clockwork Ascension",
    "filename": "Psychronic - Clockwork Ascension.mp3",
    "src": "/audio/music/Psychronic%20-%20Clockwork%20Ascension.mp3",
    "durationSeconds": 331.872
  },
  {
    "id": "psychronic-monster-arena",
    "artist": "Psychronic",
    "title": "Monster Arena",
    "filename": "Psychronic - Monster Arena.mp3",
    "src": "/audio/music/Psychronic%20-%20Monster%20Arena.mp3",
    "durationSeconds": 151.8
  },
  {
    "id": "psychronic-ritual-of-the-cosmos",
    "artist": "Psychronic",
    "title": "Ritual Of The Cosmos",
    "filename": "Psychronic - Ritual Of The Cosmos.mp3",
    "src": "/audio/music/Psychronic%20-%20Ritual%20Of%20The%20Cosmos.mp3",
    "durationSeconds": 239.592
  }
];
