import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseFile } from 'music-metadata';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const filenamePattern = /^(?<artist>.+) - (?<title>.+)\.mp3$/i;
const lobbyFilenameOverrides = new Map([
  ["Claude's Plan.mp3", { artist: 'Jeff Guo', title: "Claude's Plan" }]
]);
const catalogs = [
  {
    label: 'battle',
    musicDir: path.join(repoRoot, 'public', 'audio', 'music'),
    outputPath: path.join(repoRoot, 'shared', 'music', 'generatedBattleMusicManifest.ts'),
    exportName: 'BATTLE_MUSIC_TRACKS',
    warningLabel: '"Artist - Song Name.mp3"',
    parseNames: parseBattleFilename
  },
  {
    label: 'lobby',
    musicDir: path.join(repoRoot, 'public', 'audio', 'lobby-music'),
    outputPath: path.join(repoRoot, 'shared', 'music', 'generatedLobbyMusicManifest.ts'),
    exportName: 'LOBBY_MUSIC_TRACKS',
    warningLabel: 'a supported lobby music filename',
    parseNames: parseLobbyFilename
  }
];

async function main() {
  for (const catalog of catalogs) {
    await generateManifest(catalog);
  }
}

async function safeReadDir(dirPath) {
  try {
    return await fs.readdir(dirPath, { withFileTypes: true });
  } catch (error) {
    if (error && typeof error === 'object' && error.code === 'ENOENT') return [];
    throw error;
  }
}

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64) || 'track';
}

async function generateManifest({ label, musicDir, outputPath, exportName, warningLabel, parseNames }) {
  const entries = await safeReadDir(musicDir);
  const tracks = [];
  const skipped = [];
  const relativeDir = path.relative(path.join(repoRoot, 'public'), musicDir).replaceAll('\\', '/');

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.toLowerCase().endsWith('.mp3')) continue;
    const names = parseNames(entry.name);
    if (!names) {
      skipped.push(entry.name);
      continue;
    }

    const filePath = path.join(musicDir, entry.name);
    const metadata = await parseFile(filePath, { duration: true });
    const durationSeconds = metadata.format.duration;
    if (!Number.isFinite(durationSeconds) || durationSeconds <= 0) {
      throw new Error(`Could not read a valid duration for ${entry.name}.`);
    }

    tracks.push({
      id: slugify(`${names.artist}-${names.title}`),
      artist: names.artist,
      title: names.title,
      filename: entry.name,
      src: `/${relativeDir}/${encodeURIComponent(entry.name)}`,
      durationSeconds: Number(durationSeconds.toFixed(3))
    });
  }

  tracks.sort((a, b) => a.filename.localeCompare(b.filename));
  const body = [
    "import type { BattleMusicTrack } from './BattleMusic';",
    '',
    '// Generated by `npm run music:manifest`. Do not edit by hand.',
    `export const ${exportName}: readonly BattleMusicTrack[] = ${JSON.stringify(tracks, null, 2)};`,
    ''
  ].join('\n');

  await fs.writeFile(outputPath, body, 'utf8');

  if (skipped.length > 0) {
    console.warn(
      `[music:manifest] Skipped ${skipped.length} ${label} file(s) that do not match ${warningLabel}:\n` +
      skipped.map((name) => `  - ${name}`).join('\n')
    );
  }
  console.log(`[music:manifest] Wrote ${tracks.length} ${label} track(s) to ${path.relative(repoRoot, outputPath)}.`);
}

function parseBattleFilename(filename) {
  const match = filename.match(filenamePattern);
  if (!match?.groups?.artist || !match.groups.title) return null;
  return {
    artist: match.groups.artist.trim(),
    title: match.groups.title.trim()
  };
}

function parseLobbyFilename(filename) {
  const override = lobbyFilenameOverrides.get(filename);
  if (override) return override;

  if (!filename.toLowerCase().endsWith('.mp3')) return null;
  const stem = filename.slice(0, -4).replace(/-\d+$/, '');
  const normalized = stem.replaceAll('_', ' ');
  const tokens = normalized.split('-').map((token) => token.trim()).filter(Boolean);
  if (tokens.length < 2) return null;

  const artistTokenCount = normalized.includes('_') || normalized.includes(' ')
    ? 1
    : tokens.length >= 4
      ? 2
      : 1;
  const artist = titleCaseWords(tokens.slice(0, artistTokenCount).join(' '));
  const title = titleCaseWords(tokens.slice(artistTokenCount).join(' '));
  if (!artist || !title) return null;
  return { artist, title };
}

function titleCaseWords(value) {
  return value
    .split(/\s+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

main().catch((error) => {
  console.error('[music:manifest] Failed:', error);
  process.exitCode = 1;
});
