import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseFile } from 'music-metadata';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const musicDir = path.join(repoRoot, 'public', 'audio', 'music');
const outputPath = path.join(repoRoot, 'shared', 'music', 'generatedBattleMusicManifest.ts');
const filenamePattern = /^(?<artist>.+) - (?<title>.+)\.mp3$/i;

async function main() {
  const entries = await safeReadDir(musicDir);
  const tracks = [];
  const skipped = [];

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.toLowerCase().endsWith('.mp3')) continue;
    const match = entry.name.match(filenamePattern);
    if (!match?.groups?.artist || !match.groups.title) {
      skipped.push(entry.name);
      continue;
    }

    const filePath = path.join(musicDir, entry.name);
    const metadata = await parseFile(filePath, { duration: true });
    const durationSeconds = metadata.format.duration;
    if (!Number.isFinite(durationSeconds) || durationSeconds <= 0) {
      throw new Error(`Could not read a valid duration for ${entry.name}.`);
    }

    const artist = match.groups.artist.trim();
    const title = match.groups.title.trim();
    tracks.push({
      id: slugify(`${artist}-${title}`),
      artist,
      title,
      filename: entry.name,
      src: `/audio/music/${encodeURIComponent(entry.name)}`,
      durationSeconds: Number(durationSeconds.toFixed(3))
    });
  }

  tracks.sort((a, b) => a.filename.localeCompare(b.filename));
  const body = [
    "import type { BattleMusicTrack } from './BattleMusic';",
    '',
    '// Generated by `npm run music:manifest`. Do not edit by hand.',
    `export const BATTLE_MUSIC_TRACKS: readonly BattleMusicTrack[] = ${JSON.stringify(tracks, null, 2)};`,
    ''
  ].join('\n');

  await fs.writeFile(outputPath, body, 'utf8');

  if (skipped.length > 0) {
    console.warn(
      `[music:manifest] Skipped ${skipped.length} file(s) that do not match "Artist - Song Name.mp3":\n` +
      skipped.map((name) => `  - ${name}`).join('\n')
    );
  }
  console.log(`[music:manifest] Wrote ${tracks.length} track(s) to ${path.relative(repoRoot, outputPath)}.`);
}

async function safeReadDir(dirPath) {
  try {
    return await fs.readdir(dirPath, { withFileTypes: true });
  } catch (error) {
    if (error && typeof error === 'object' && error.code === 'ENOENT') return [];
    throw error;
  }
}

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64) || 'track';
}

main().catch((error) => {
  console.error('[music:manifest] Failed:', error);
  process.exitCode = 1;
});
